version: 2
_job:
    docker:
        - image: debian:stretch
    steps:
        - checkout
        - run:
              name: Install system dependencies
              command: apt update -y && apt install -y libfontconfig1 make perl-doc wget
        - restore_cache:
              key: v1-{{ checksum "packages.txt" }}
        - run:
              name: Install minimal TeXLive
              command: sudp apt update && sudo apt install texlive-base
        - run:
              name: Install package dependencies
              command: ./bin/install-packages packages.txt
        - save_cache:
              key: v1-{{ checksum "packages.txt" }}
              paths:
                  - ~/.texlive
                  - /srv/texlive
        - run:
              name: Add TeXLive to PATH
              command: echo 'export PATH="/srv/texlive/bin/x86_64-linux:${PATH}"' >>$BASH_ENV
        - run:
              name: Compile document
              command: make
jobs:
    lint:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: npm ci
            - run: make lint
    pdflatex:
        docker:
            - image: debian:stretch
        steps:
            - checkout
            - run:
                  name: Install system dependencies
                  command: apt update -y && apt install -y libfontconfig1 make perl-doc wget
            - restore_cache:
                  key: v1-{{ checksum "packages.txt" }}
            - run:
                  name: Install minimal TeXLive
                  command: sudp apt update && sudo apt install texlive-base
            - run:
                  name: Install package dependencies
                  command: ./bin/install-packages packages.txt
            - save_cache:
                  key: v1-{{ checksum "packages.txt" }}
                  paths:
                      - ~/.texlive
                      - /srv/texlive
            - run:
                  name: Add TeXLive to PATH
                  command: echo 'export PATH="/srv/texlive/bin/x86_64-linux:${PATH}"' >>$BASH_ENV
            - run:
                  name: Compile document
                  command: make
        environment:
            - LATEX: pdflatex
    lualatex:
        docker:
            - image: debian:stretch
        steps:
            - checkout
            - run:
                  name: Install system dependencies
                  command: apt update -y && apt install -y libfontconfig1 make perl-doc wget
            - restore_cache:
                  key: v1-{{ checksum "packages.txt" }}
            - run:
                  name: Install minimal TeXLive
                  command: sudp apt update && sudo apt install texlive-base
            - run:
                  name: Install package dependencies
                  command: ./bin/install-packages packages.txt
            - save_cache:
                  key: v1-{{ checksum "packages.txt" }}
                  paths:
                      - ~/.texlive
                      - /srv/texlive
            - run:
                  name: Add TeXLive to PATH
                  command: echo 'export PATH="/srv/texlive/bin/x86_64-linux:${PATH}"' >>$BASH_ENV
            - run:
                  name: Compile document
                  command: make
        environment:
            - LATEX: lualatex
    xelatex:
        docker:
            - image: debian:stretch
        steps:
            - checkout
            - run:
                  name: Install system dependencies
                  command: apt update -y && apt install -y libfontconfig1 make perl-doc wget
            - restore_cache:
                  key: v1-{{ checksum "packages.txt" }}
            - run:
                  name: Install minimal TeXLive
                  command: ./bin/install-texlive
            - run:
                  name: Install package dependencies
                  command: ./bin/install-packages packages.txt
            - save_cache:
                  key: v1-{{ checksum "packages.txt" }}
                  paths:
                      - ~/.texlive
                      - /srv/texlive
            - run:
                  name: Add TeXLive to PATH
                  command: echo 'export PATH="/srv/texlive/bin/x86_64-linux:${PATH}"' >>$BASH_ENV
            - run:
                  name: Compile document
                  command: make
        environment:
            - LATEX: xelatex
workflows:
    version: 2
    build:
        jobs:
            - lint
            - pdflatex
            - lualatex
            - xelatex
